export const CLIENT = {
    FETCH_CLIENT: 'FETCH_CLIENT',
    FETCH_CLIENT_DONE: 'FETCH_CLIENT_DONE',
    SAVE: 'SAVE',
    SAVE_DONE: 'SAVE_DONE',
    DELETE: 'DELETE',
    DELETE_DONE: 'DELETE_DONE',
    UPDATE: 'UPDATE',
    FILTER: 'FILTER',
    RESET: 'RESET',
    OPEN_DIALOG: 'OPEN_DIALOG',
    OPEN_ALERT: 'OPEN_ALERT',
    SET_ERROR: 'SET_ERROR',
};